name : Github Action Demo
on : push
jobs : 
  Premier-Jobs :
    name : Premier Job
    runs-on : Ubuntu-latest
    steps :
      - run : echo "Premier Job"
      - run : echo "Fin"
  Second-Jobs :
    name : Second Job
    runs-on : Ubuntu-latest
    needs : Premier-Jobs
    steps :
      - run : echo "Second Job"
      - run : echo "Fin"
